### ISSUE TITLE
Connexion impossible - Version2019-11-14 21:17:16

### ISSUE THREAD

**Issue by FlorianHergo** [foulek57/jeedom-ewejee#1]
Bonjour,

Je viens d'acheter votre plugin sur Jeedom ce soir.
Malheureusement il ne veut pas se connecter à mon compte : Echec d'authentification, veillez vérifier vos identifiants
J'ai pourtant changé le password et regénéré un nouveau.
Il y aurait il un soucis dans la  MAJ ?

J'ai l'impression que je n'arrive pas à avoir votre derniere MAJ de ce soir ?

Jeedom : 4.0.27

**Comment by FlorianHergo** [comment]
J'ai réussi, il suffit de lire votre documentation. Merci bien !
Par contre je n'arrive pas à savoir si j'ai bien la version 1.1 car je vois uniquement : 2019-11-14 21:17:16

**Comment by foulek57** [comment]
Bonsoir,

Merci pour l'achat :) 

La V1.1 est en beta pour le moment, le temps de tester, et passera en stable une fois que j'aurais tous les retours. 
Pour le passage à la V1.1 il faudra réinstaller les dépendances et refaire une synchronisation complete.

**Comment by homefefeld** [comment]
je me retrouve avec une erreur : 
<img width="939" alt="ERROR" src="https://user-images.githubusercontent.com/3512839/69447481-e7787080-0d56-11ea-85dd-92368cc5c724.png">
Apparement la column json_nb_array n'existe pas dans la version Jeedom 3.3.30 ;(
Je ne peux pas updater mon système de production.
Je vais devoir flasher la mon Sonoff ...

**Comment by foulek57** [comment]
Bonjour,

Pas forcément, je vais faire des test du cette version, je vous tiens au courant.

**Comment by homefefeld** [comment]
Bah, Je fais quoi ?

**Comment by homefefeld** [comment]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/3512839/69637513-10e81380-1059-11ea-8e7f-471dbeb01f88.png">

**Comment by homefefeld** [comment]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/3512839/69637628-51e02800-1059-11ea-8df3-846c2519defc.png">
voila la table eqLogic, c'est different à partir de quelle version ?

**Comment by foulek57** [comment]
Deux personnes l'utilisent sur la v 3.3.38 et c'est fonctionnel, j'ai installé une VM que je vais voir pour mettre en v3.3.30 et faire des tests, je vous tiens informé

**Comment by foulek57** [comment]
Bonjour,

Ça fonctionne correctement aussi sur la v3.3.30.
Avez vous fait la dernière mise a jour ? Avez vous toujours le problème ?
