### ISSUE TITLE
Module volet KingArt KING-Q4

### ISSUE THREAD

**Issue by jayjay490** [foulek57/jeedom-ewejee#11]
Bonjour, j'ai acheté des modules pour volets KingArt KING-Q4 couplé sur EWEJEE. Tout est OK, il remonte bien sur jeedom. Là où sa se complique c'est au niveau des commande.
Je me retrouve avec une ON, une OFF et une Statut. Il me manque le bouton pause ....
Donc si j'en crois mon pifométre lol, 524 correspond à OFF (donc fermeture), 523 à ON (ouverture), et 525 à l'état. Je pense donc qu'il faudrai ajouter soit la commande 522 pour PAUSE soit la 526 ...
Est-ce possible ? J'en ai acheté 8 quand même ...

**Comment by foulek57** [comment]
Bonjour,
Il est dans ma todo liste, je le passe en priorité.
Il y aura une commande +10% et une commande -10% de prévu car d'après les données que j'ai, la position du volet de règle en pourcentage.

Je pourrais améliorer cela si vous êtes disponible pour faire des tests.

Je ne suis pas disponible ces prochains jours donc il faudra être patient.

Merci

**Comment by jayjay490** [comment]
oui en effet le volet, sur l'appli, se regle soit en ON OFF soit avec une slide bar. Quand on branche la prise, pour la 1ere utilisation il est necessaire de la calibrer en la fermant à fond et en ouvrant le volet. d'aprés la notice, la prise calcule le temps de monté de descente pour pouvoir jouer avec la slide bar et donc, je pense, en pourcentage.
Je serai ravis d'affectuer les tests si necessaire.
Mais pas de panique sur le temps, lol pour le moment, ils font le boulot en scenario en s'ouvrant le matin et se fermant le soir.

**Comment by foulek57** [comment]
Merci pour ces informations, mais je ne comprends pas très bien 
On ouvre le volet et off le ferme ?

**Comment by jayjay490** [comment]
Bonjour, ce sera plus clair en images je pense.
https://zupimages.net/up/20/06/vekn.jpg
https://zupimages.net/up/20/06/ts2b.jpg
https://zupimages.net/up/20/06/mpxg.jpg
https://zupimages.net/up/20/06/pk0j.jpg
https://zupimages.net/up/20/06/vwo5.jpg

Du coup sur votre plugin, ON correspond à OPEN et OFF correspond à CLOSE. Il manque la fonction PAUSE pour une utilisation dite classique.

**Comment by foulek57** [comment]
Alors on va faire une chose pour que je voie quel est l'action pour le pause, car dans les paramètres je ne vois pas.

Pouvez-vous faire cela dans ces ordre précis :
Vider le log ewejee_node.
Ouvrir le volet entièrement,
Le fermer et faire pause avant la fermeture complète.

Vous pouvez ensuite mettre le log ici en supprimant l'apikey et votre ip

**Comment by jayjay490** [comment]
Bonjour, voici le résultat de la manip.


PONG
Date : Mon Feb 10 2020 18:42:48 GMT+0100 (Central European Standard Time)
Début des données String
"pong"
Fin des données String
Date : Mon Feb 10 2020 18:42:59 GMT+0100 (Central European Standard Time)
Début des données String
{"action":"update","deviceid":"xxxxxx","apikey":"xxxxxxxxx","userAgent":"device","ts":0,"params":{"switch":"on","setclose":100},"from":"device"}
Fin des données String
Date : Mon Feb 10 2020 18:43:29 GMT+0100 (Central European Standard Time)
Début des données String
{"action":"update","deviceid":"xxxxxxx","apikey":"xxxxxxxxxxx","userAgent":"device","ts":0,"params":{"switch":"on","setclose":0},"from":"device"}
Fin des données String
Date : Mon Feb 10 2020 18:43:30 GMT+0100 (Central European Standard Time)
Début des données String
{"action":"update","deviceid":"xxxxx","apikey":"xxxxxxxx","userAgent":"device","ts":0,"params":{"switch":"off","setclose":0},"from":"device"}
Fin des données String
Date : Mon Feb 10 2020 18:43:46 GMT+0100 (Central European Standard Time)
Début des données String
{"action":"update","deviceid":"xxxxxx","apikey":"xxxxxxxxx","userAgent":"device","ts":0,"params":{"switch":"pause","setclose":51},"from":"device"}
Fin des données String

**Comment by foulek57** [comment]
Le King Q4 a été ajouté.
