### ISSUE TITLE
Commande statut

### ISSUE THREAD

**Issue by jean2979** [foulek57/jeedom-ewejee#13]
Bonjour, merci pour ce super plugin, est-il envisageable d'ajouter une commande concernant le statut ? (Online/Offline)
Merci

**Comment by foulek57** [comment]
Bonjour,

Oui c'est possible, mais le statut offline n'est que détecté quand on envoie une commande et qu'il n'y a pas de réponse, donc c'est pas une info fiable a 100% et c'est pour cette raison que je ne l'ai pas ajouté dans les commandes

**Comment by jean2979** [comment]
Sur la page "équipement" on a bien l'info non ?

**Comment by foulek57** [comment]
Oui c'est ce que je dit, mais ce n'est pas du 100% je l'ai mis a titre d'information, si je le met dans les commandes, ça serra erroné si on ne lancé pas de commande.

**Comment by jean2979** [comment]
Je souhaitais faire un suivi online/offline, peut être on peut le faire depuis l'ip ?

**Comment by foulek57** [comment]
Bien-sûr avec le plugin network tu peux historiser le ping sur IP ;)
