### ISSUE TITLE
demon nok

### ISSUE THREAD

**Issue by jungle25** [foulek57/jeedom-ewejee#15]
slt foulek57

J'utilise ton plugin ewejee depuis le debut ,mais depuis un moment il ne fonctionne plus .

[ewejee_dep.txt](https://github.com/foulek57/jeedom-ewejee/files/4761365/ewejee_dep.txt)
[ewejee_node.txt](https://github.com/foulek57/jeedom-ewejee/files/4761376/ewejee_node.txt)

si tu as une idées....Merci

**Comment by foulek57** [comment]
Hello,

l'IP pour accéder à ton jeedom est http://192.168.86.92 ??

Si c'est pas ça il faut modifier l'adresse interne dans la configuration de Jeedom.

**Comment by jungle25** [comment]
Merci pour ta reponse  express ....

C'est bien l'adresse que j'utilise pour accéder a mon jeedom.

**Comment by jungle25** [comment]
J'ai essayé de réinstaller le plugin sans resultat..
J'ai essayé de lancé le demon plusieurs fois sans succès.....
J'accède a mon compte avec l'application sans problème.....
J'ai configuré le plugin en http ( depuis le début )mais depuis peu ya pas moyen.....

Tu vois quelque chose dans les logs qui te parle ?


Je m'en remet a toi ....

Merci

**Comment by foulek57** [comment]
Hello,

J'ai jamais eu cette erreur et personne ne le la jamais reporté.

Tu peux me donner un peu plus d'info sur ton installation ?
La machine ou est monté Jeedom
Ton type de réseaux, si tu as fermé des ports ou configuré un firewall ?

Le websocket n'arrive pas a se connecter.

**Comment by jungle25** [comment]
Re...mon installation tourne sur un rpi 3B avec la dernière version en date de jeedom ainsi que la dernière version de ton plugin.
Toute mon installation est connectée a un reseau google wifi(box + capteurs+etc)
Pas de firewall...port ouvert 80 UDP pour jeedom..je n'ai absolulent rien touché depuis 1 ans et le reste des plugins utilisés dans jeedom fonctionnent parfaitement. 
Etant un utilisateur somme toute "novice",si je peux te donner des infos plus précises ,hesite pas a me les demander

**Comment by foulek57** [comment]
Si ça ne te dérange pas, on peut discuter par chat (WhatsApp, Facebook Messenger etc...)
Si tu est d'accord, tu peux m'envoyer un mail avec ton contact pour ta messagerie préfèrée a wn68320@gmail.com.
