### ISSUE TITLE
Impossible de lancer le demon

### ISSUE THREAD

**Issue by Gougou78** [foulek57/jeedom-ewejee#2]
Bonjour,

Je viens d'installer le plugin, j'ai relancé l'installation des dépendances puis attendue 10min.
J'ai ensuite renseigné mes identifiants eWelink et j'ai sauvegardé puis relancer le demon.

Cependant le demon ne veut pas se lancer : "[2019-12-06 09:53:16][ERROR] : Impossible de lancer le démon ewejee, vérifiez le port"

![Capture jeedom](https://user-images.githubusercontent.com/47254385/70311044-2acfe600-1811-11ea-952c-e888487d6451.PNG)

Voici les logs : 
[ewejee.txt](https://github.com/foulek57/jeedom-ewejee/files/3931322/ewejee.txt)
[ewejee_dep.txt](https://github.com/foulek57/jeedom-ewejee/files/3931327/ewejee_dep.txt)
[ewejee_node.txt](https://github.com/foulek57/jeedom-ewejee/files/3931328/ewejee_node.txt)

Merci d'avance :)

**Comment by foulek57** [comment]
Bonjour,

Merci pour les log, pouvez vous me dire sur quelle machine vous avez installé Jeedom ?

**Comment by Gougou78** [comment]
J'ai installé Jeedom sur une Raspberry Pi 3B+, j'ai changé le port de Apache et par conséquent supprimé le port 80. Peut-être que le problème vient de là ?

**Comment by foulek57** [comment]
Oui, ca viens de la, l'installation à bien fonctionné, et dans les log je vois que la connexion est refusé sur le port 80, je ne sais pas si je peux changer cela car j'utilise le module "request" que je ne peux pas modifier.

Avez vous un moyen de remettre le port 80 ?

Quel est l'intéret d'avoir changé de port ?

**Comment by Gougou78** [comment]
J'ai changé le port de Jeedom pour l'accès extérieur, pour pouvoir ouvrir un port de ma box autre que le 80, pour des questions de sécurité. S'il n'y a pas d'alternative possible je remetterai le port 80.

Merci

**Comment by foulek57** [comment]
En effet c'est le port qui pose problème, sur la prochaine mise a jour je donnerais la possibilité de mettre un port différent

**Comment by foulek57** [comment]
La mise a jour est en ligne pour modifier le port.
