### ISSUE TITLE
plugin ne s'installe pas

### ISSUE THREAD

**Issue by pouda** [foulek57/jeedom-ewejee#3]
Bonjour,

je viens d'acheter le plugin, j'arrive à l'installer sur Jeedom par contre il y'a des erreurs à l'installation des dépendances et il n'arrive pas à démarrer
J'ai tester la version stable et la beta ... même problème... 
Je pense qu'il y'a un soucis à l'installation de l'api et du reste... bref les fichiers de log sont en PJ...si vous pouviez m'aider ce serait sympe :)

Merci

[ewedjee.zip](https://github.com/foulek57/jeedom-ewejee/files/3963873/ewedjee.zip)

**Comment by foulek57** [comment]
Essayez de redémarrer jeedom, d'après les log le serveur n'arrive pas a ce lancer car le port est déjà utilisé.

**Comment by pouda** [comment]
quel est le numéro de port utilisé ? et dans quel sens ?

**Comment by pouda** [comment]
alors le plugin a démarré, par contre j'ai l'impression qu'il ne me retourne pas les valeurs du boitier (TH16 + Sonde Si7021)

**Comment by foulek57** [comment]
Le port est le 6005.
Il me faudrait les nouveaux log du coup pour voir pourquoi ça ne remonte pas

**Comment by pouda** [comment]
ahh, je viens de lire la doc en détails... il faut 2 comptes ewelink... j'ai resynchro et j'ai de nouveau les données... par contre, cela synchronise toutes les combien de minutes ?

**Comment by pouda** [comment]
et faut-il activer la gestion automatique dans le plugin ?

**Comment by pouda** [comment]
il y'a bien un souci .. la remonter de la température ne se fait que quand je synchronise manuellement ....

**Comment by pouda** [comment]
au final .. je m’aperçois que les valeurs sont bien récupérer par le plugin mais le test ne renvoi pas la bonne valeur.

Exemple ci-dessous 
Date : Sat Dec 14 2019 19:20:35 GMT+0100 (CET)
Début des données String
{"action":"update","deviceid":"1000972db3","apikey":"7fa3d268-ab3a-4074-b00f-63fa86015273","userAgent":"device","ts":0,"params":{"currentTemperature":"**42**"},"from":"device"}
Fin des données String

et si j'execute le test depuis le plugin cela me renvoi 34°

Résultat de la commande : 34

**Comment by foulek57** [comment]
Avez vous un port différents de 80 sur localhost ?

**Comment by foulek57** [comment]
J'ai mis en place une récupération du port utilisé pour jeedom sur la dernière version (en bêta actuellement) cela corrige ce problème.

**Comment by pouda** [comment]
ca fonctionne nettement mieux merci !
