### ISSUE TITLE
pb installation plugin

### ISSUE THREAD

**Issue by lezardvert31** [foulek57/jeedom-ewejee#5]
bonjour,
j'essaie en vain d'installer le plugin ,les dépendances presentent des erreurs. c'est un jeedom sur Freebox delta.

[ewejee_dep.zip](https://github.com/foulek57/jeedom-ewejee/files/4008745/ewejee_dep.zip)

Merci.

**Comment by foulek57** [comment]
Bonjour,

Il semblerait qu'il y ait un problème avec les sudoers, avez vous modifié des droit ou le fichier etc/sudoers.d ?

**Comment by lezardvert31** [comment]
j'ai réinstallé la VM, les dépendances se sont installés.
maintenant il y a un pb de port, le demon ne veut pas se lancer.
le port du demon est fixe ou il est possible de le changer?

**Comment by lezardvert31** [comment]
Après réinstallation de la vm, tout est rentré dans l'ordre.

Merci.

**Comment by foulek57** [comment]
Parfait, et pour info il sera possible de changer le port sur la prochaine mise a jour.
