### ISSUE TITLE
TH16 : les données température et humidité se figent

### ISSUE THREAD

**Issue by vercoutt** [foulek57/jeedom-ewejee#6]
Bonjour, 

J'ai installé 1xTH16 avec sonde de température et 2xTH16 avec sonde de température+humidité
Cela fonctionne bien les premières heures mais ensuite les données (température et humidité) se figent.

La commande à distance (ON/OFF) depuis Jeedom fonctionne bien.

L'application Ewelink montre les bonnes données qui continuent de varier.

Si nécessaire, je peux vous partager un des équipements

Cordialement
Thibault

**Comment by foulek57** [comment]
Bonjour,

Quand les infos figent, pouvez vous voir si vous avez une erreur dans le log ewejee_node.

Je rappel que si vous êtes connecté sur votre compte eWeLink sur le smartphone, cela deconnecte le plugin (c'est ce qui doit ce passer) le commandes fonctionnent toujours mais les info ne sont plus transmises au plugin.

**Comment by vercoutt** [comment]
Bonjour,
J'ai bien 2 comptes séparés.
J'ai regardé le log, il y a la même erreur qui se répète, j'en ai copié un extrait ci-dessous.

(node:20317) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1093)
(node:20317) UnhandledPromiseRejectionWarning: Error: Can't send data because WebSocket is not opened.
at exports.throwIf (/var/www/html/plugins/ewejee/core/js/node_modules/websocket-as-promised/dist/index.js:3470:11)
at WebSocketAsPromised.send (/var/www/html/plugins/ewejee/core/js/node_modules/websocket-as-promised/dist/index.js:554:7)
at Timeout._onTimeout (/var/www/html/plugins/ewejee/core/js/newserver.js:212:20)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)

**Comment by foulek57** [comment]
Bonjour et bonne année

C'est en effet le "Socket" qui est déconnecté, il faut relancer le démon pour le reconnecter.

Si vous avez un second compte, il ne faut pas que eWeLink soit lancé, ni qu'elle tourne en arrière plan, j'avais cette erreur même quand l'appli était fermée, j'ai du désinstaller l'appli sur ma tablette (mon second compte) et depuis 3 semaine je n'ai pas été déconnecté.

**Comment by vercoutt** [comment]
Merci pour vos réponses rapides et bonne année également.

Alors, du coup je ne comprends pas : l’intérêt du 2e compte c'est pour utiliser l'appli et jeedom en parallèle non?

Le redémarrage du demon ne change rien, en revanche le débranchement/rebranchement d'un appareil remet à jour les données sur Jeedom mais juste une fois, après ça reste figé.

**Comment by foulek57** [comment]
Dans ce cas c'est peut être un autre soucis.
Pouvez vous redémarrer le démon et quand l'erreur apparaît dans les log, m'envoyer le log ewejee_node par mail a wn68320@gmail.com ?

**Comment by foulek57** [comment]
J'ai bien reçu le log.
Mais je ne vois pas de trace du redémarrage du démon.
Avez-vous essayé de redémarrer jeedom ?

**Comment by vercoutt** [comment]
Bonjour,

OK, je viens de redémarrer Jeedom, puis j'ai vidé le log du plugin, puis
j'ai redémarré le demon.
Là ça fonctionne, je laisse tourner jusqu'au prochain bloquage avant de
vous renvoyer le log.
Et hier je me suis déconnecté de l'appli et je l'ai killée. Je ne me
reconnecte pas sur l'appli pour l'instant pour mettre de côté l'hypothèse
du multi accès.

Bonne journée.

**Comment by foulek57** [comment]
Bonjour,

Je viens au nouvelles, le démon tourne ?

**Comment by vercoutt** [comment]
Bonjour, depuis le redémarrage de jeedom ET la non utilisation de l'appli eWeLink ça fonctionne, les données ne se figent plus. Je vais me reconnecter avec l'appli (sur un compte séparé pour voir si cela a une incidence).

Merci pour votre réactivité permanente 👍

**Comment by foulek57** [comment]
Parfait, j'attends votre retour si ça plante alors que vous nêtes pas connecté sur le compte, je vais voir d'où viens la déco.

**Comment by foulek57** [comment]
Bonjour, je reviens au nouvelles ?

**Comment by vercoutt** [comment]
Bonjour,
Merci pour votre suivi!

Pour l'instant plus aucun problème, mes 3 capteurs Température et Humidité. 
Il y a eu beaucoup de mise à jour et j'ai entièrement ré installé mon JeeDom.

**Comment by vercoutt** [comment]
Bonjour,

Le 10 janvier j'ai entièrement ré-installé JeeDom et tout fonctionnait jusqu'à hier 20h avec cette erreur qui se répète :

at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)
(node:5331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 435)
(node:5331) UnhandledPromiseRejectionWarning: Error: Can't send data because WebSocket is not opened.
at exports.throwIf (/var/www/html/plugins/ewejee/core/js/node_modules/websocket-as-promised/dist/index.js:3470:11)
at WebSocketAsPromised.send (/var/www/html/plugins/ewejee/core/js/node_modules/websocket-as-promised/dist/index.js:554:7)
at Timeout.setInterval [as _onTimeout] (/var/www/html/plugins/ewejee/core/js/newserver.js:691:20)
at ontimeout (timers.js:498:11)

**Comment by vercoutt** [comment]
Suite à ça j'ai relancé le demon et j'ai ça :

Serveur correctement lancé sur http://localhost:6005 Le Wed Jan 22 2020 11:02:47 GMT+0000 (UTC)
Date : Wed Jan 22 2020 11:02:51 GMT+0000 (UTC)
Début des données String
{"error":406,"sequence":"1579690970047"}
Fin des données String
(node:13876) UnhandledPromiseRejectionWarning: Error: Can't send data because WebSocket is not opened.
at exports.throwIf (/var/www/html/plugins/ewejee/core/js/node_modules/websocket-as-promised/dist/index.js:3470:11)
at WebSocketAsPromised.send (/var/www/html/plugins/ewejee/core/js/node_modules/websocket-as-promised/dist/index.js:554:7)
at Timeout.setInterval [as _onTimeout] (/var/www/html/plugins/ewejee/core/js/newserver.js:691:20)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)
(node:13876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13876) UnhandledPromiseRejectionWarning: Error: Can't send data because WebSocket is not opened.
at exports.throwIf (/var/www/html/plugins/ewejee/core/js/node_modules/websocket-as-promised/dist/index.js:3470:11)
at WebSocketAsPromised.send (/var/www/html/plugins/ewejee/core/js/node_modules/websocket-as-promised/dist/index.js:554:7)
at Timeout.setInterval [as _onTimeout] (/var/www/html/plugins/ewejee/core/js/newserver.js:691:20)


Et ça ne fonctionne toujours pas.

Redémarrage de JeeDom  Et ça ne fonctionne toujours pas.


ça ne serait pas à cause de la dernière mise à jour?

**Comment by foulek57** [comment]
Je n'ai rien changé de ce côté, l'erreur 406 arrive quand l'identifiant n'est pas bon, avez vous bien remis l'adresse email ? Le numéro de téléphone ne fonctionne pas

**Comment by vercoutt** [comment]
Ah ok,, lors de l'installation de la mise à jour le login était admin... J'ai remis l'email et le mot de passe c'est reparti!

Merci et bravo pour les dév à venir annoncés dans le changelog!

**Comment by foulek57** [comment]
Parfait ! Merci, je ferme cet issue
