### ISSUE TITLE
Ampoules B1

### ISSUE THREAD

**Issue by franck57fr** [foulek57/jeedom-ewejee#7]
Bonjour,
j'ai 3 ampoules SonOff B1 que je n'arrive pas à commander.

Merci par avance pour votre aide.

**Comment by foulek57** [comment]
Bonsoir,

Pouvez vous supprimer l'équipement vider le log "ewejee_node" puis faire une synchronisation (une seule) et m'envoyer ce log par mail ?

Je vais devoir inclure la partie pour changer la couleur de l'ampoule et la luminosité, mais pour cela il me faut le log.

**Comment by franck57fr** [comment]
Bonjour,
Merci pour votre message.
pour plus de précision, les 3 ampoules sont bien détectées cependant je n'arrive pas à les commandées.
Dans l'équipement (onglet commandes) je n'ai que la partie "Créateur de couleur (Uniquement pour WI16)"
Voici le log d'une des ampoules incriminée :
Merci encore pour votre aide
========LOG=========
settings: { opsNotify: 0, opsHistory: 1, alarmNotify: 1 },
group: '',
online: true,
groups: [ '59ad5c82a679953b503cf316' ],
devGroups: [],
_id: '5bb35e86b7623dd1033cea28',
name: 'Buffet',
type: '10',
deviceid: '10001c4f76',
apikey: 'c3281c86-5849-4388-98b8-46749d183253',
extra: { extra: [Object], _id: '59e458c75c1af3a660cdd392' },
createdAt: '2018-10-02T12:03:18.203Z',
__v: 0,
onlineTime: '2020-01-13T10:08:44.306Z',
ip: 'XX.XXX.X.XXX',
location: '',
params: {
state: 'on',
channel2: '0',
channel1: '25',
fwVersion: '2.6.0',
channel0: '0',
channel4: '0',
channel3: '0',
staMac: '60:01:94:97:FC:88',
rssi: -55,
controlType: 8,
partnerApikey: 'afe4bba9-5003-4873-bdac-89abf4d377e3',
zyx_mode: 1,
type: 'warm',
timers: [],
bindInfos: [Object]
},
offlineTime: '2020-01-13T09:55:06.022Z',
deviceStatus: '',
tags: { disable_timers: [] },
sharedBy: {
email: 'franck57fr@gmail.com',
apikey: 'c3281c86-5849-4388-98b8-46749d183253',
permit: 15,
shareTime: 1578743396189
},
devicekey: '754729f9-d791-4482-baf2-9d3b442b9548',
deviceUrl: 'https://eu-api.coolkit.cc/api/detail/5927cd536ea4362d439a1d7a_en.html',
brandName: 'Sonoff',
showBrand: true,
brandLogoUrl: 'https://eu-ota.coolkit.cc/logo/KRZ54OifuGmjoEMxT1YYM3Ybu2fj5K2C.png',
productModel: 'B1',
devConfig: {},
uiid: 22

**Comment by franck57fr** [comment]
Bonjour, je vous fais cela de suite.

Merci d'avance

**Comment by franck57fr** [comment]
Suite à votre demande voici le log pour l'ampoule sonoff B1.

Merci encore
===LOG===

>

**Comment by foulek57** [comment]
Merci pour les infos.
Les paramètres ne sont pas très clair il faudrait me faire des test.

Pouvez vous dans cet ordre : 
Vider le log ewejee_node
Ouvrir l'application eWeLink
Allumer puis étendre la lumière
Allumer la lumière
Changer la couleur de la lumière
Descendre progressivement l'intensité.

Si vous pouvez m'envoyer le log par mail wn68320@gmail.com
