### ISSUE TITLE
problème de daemon depuis update 1.1.4

### ISSUE THREAD

**Issue by raidencorp** [foulek57/jeedom-ewejee#9]
Hello,

Voilà j'utilise ewelink depuis quelques temps mais depuis l'update 1.1.4 j'ai des problèmes de daemon, impossible de le relancer et donc plus rien ne fonctionne (logique). Je travaille en interne en http sur le port 80. J'ai refais plusieurs fois l'installation des dépendances et j'ai même supprimé et réinstallé le plugin mais rien n'y fait.
Je suis toujours en V3.3.39 (je ne passerai en V4 que lorsqu'une stable sera sortie).
Les logs sont en attachment ;).

Merci d'avance
[Ewejee logs.zip](https://github.com/foulek57/jeedom-ewejee/files/4143006/Ewejee.logs.zip)

**Comment by foulek57** [comment]
Hello, 

Jeedom est installé sur une smart ? Ou raspberry ?

**Comment by raidencorp** [comment]
Il est installé sur un Rpi3b+.
Mais je viens encore une fois de relancer l'installation des dépendances juste avant de manger et cela refonctionne mais je ne comprends pas du tout pourquoi, je n'ai pourtant fait aucune modification depuis les autres fois. J'annexe quand même le dernier log des dépendances si ça peut aider.

Bien à toi
[ewejee_dep.zip](https://github.com/foulek57/jeedom-ewejee/files/4143157/ewejee_dep.zip)

**Comment by foulek57** [comment]
Ah.. étrange au vu du script l'installation n'a pas fonctionné pour nodejs, je vais changer le script d'installation.
Ah tu installé autre chose entre les deux essais ? Un autre plugin ?

**Comment by raidencorp** [comment]
Absolument rien, j'ai juste été manger

**Comment by foulek57** [comment]
Étrange ceci, merci pour ta réponse.

**Comment by raidencorp** [comment]
Hello, si jamais ça peut aider, j'ai trouvé le problème: ma version de Jeedom était encore sous Jessie et en la passant en Buster je n'ai plus eu de soucis au niveau des dépendances ;).

**Comment by foulek57** [comment]
Merci pour cette info précieuse, je vais vérifier ce que fait l'installation sur Jessie.
